---
- name: Ensure docker-compose is installed
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Remove service
  docker_swarm_service:
    name: ddns_cloudflare-ddns
    state: absent
  ignore_errors: true

- name: Setup DDNS directory
  ansible.builtin.file:
    path: /home/docker-compose/ddns
    state: directory
    mode: '0755'
    owner: nobody
    group: nogroup

- name: Copy compose from template to host
  ansible.builtin.template:
    src: "templates/docker-compose.yml"
    dest: "/home/docker-compose/ddns/docker-compose.yaml"
    mode: '0755'
    owner: nobody
    group: nogroup

- name: Deploy DDNS stack
  ansible.builtin.command:
    cmd: docker stack deploy -c /home/docker-compose/ddns/docker-compose.yaml ddns
  register: swarm_check
  changed_when: false

- name: delete compose directory
  ansible.builtin.command:
    cmd: rm -rf /home/docker-compose 