---
- name: Start Traefik
  community.docker.docker_compose_v2:
    project_src: /home/docker-compose/traefik
    state: present
    restarted: true

- name: delete compose directory
  ansible.builtin.command:
    cmd: rm -rf /home/docker-compose 