---
docker_apt_release_channel: "stable"
docker_apt_repository: "deb [arch={{ deb_architecture.stdout }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
docker_daemon_options:
  storage-driver: "overlay2"