---
# =============================================================================
# RESTIC NFS BACKUP CONFIGURATION VARIABLES
# =============================================================================
#
# This file contains the configuration variables required for the NFS backup
# solution using Restic. All sensitive values are stored in Ansible Vault
# and referenced using the vault_* variables pattern for security.

# -----------------------------------------------------------------------------
# ENCRYPTION CONFIGURATION
# -----------------------------------------------------------------------------
# Encryption key used to secure the Restic backup repository
# This password protects all backup data and is essential for restoration
#
# SECURITY WARNINGS:
# - Never store the actual encryption key in version control
# - Store a secure copy in an offline location (disaster recovery)
# - Loss of this key makes ALL backups permanently inaccessible
# - There is NO recovery mechanism if this key is lost
nfs_encryption_key: "{{ vault_nfs_encryption_key }}"

# -----------------------------------------------------------------------------
# S3 STORAGE CONFIGURATION
# -----------------------------------------------------------------------------
# S3-compatible storage backend configuration for Restic
# These settings define where backup data will be stored remotely
#
# BUCKET CONFIGURATION:
# - The bucket must already exist before starting backup operations
# - Verify proper bucket lifecycle policies to manage storage costs
# - Consider enabling versioning for additional data protection
nfs_s3_bucket: "{{ vault_nfs_s3_bucket }}"  # S3 bucket URL (e.g., s3:https://endpoint/bucket-name)
nfs_s3_region: "{{ vault_nfs_s3_region }}"  # AWS/S3 region (e.g., us-east-1)

# S3 AUTHENTICATION:
# - Use dedicated access keys with least privilege principle
# - IAM permissions needed: s3:ListBucket, s3:PutObject, s3:GetObject, s3:DeleteObject
# - Recommend creating a dedicated IAM user specifically for backups
nfs_s3_key_id: "{{ vault_nfs_s3_key_id }}"        # S3 access key ID
nfs_s3_access_key: "{{ vault_nfs_s3_access_key }}" # S3 secret access key


