---

- name: Ensure docker-compose is installed
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Remove backup service
  docker_swarm_service:
    name: nfs_backup_restic_backup
    state: absent
  ignore_errors: true

- name: Remove prune service
  docker_swarm_service:
    name: nfs_backup_restic_prune
    state: absent
  ignore_errors: true

- name: Remove check service
  docker_swarm_service:
    name: nfs_backup_restic_check
    state: absent
  ignore_errors: true

- name: Setup restic directory
  ansible.builtin.file:
    path: /home/docker-compose/restic
    state: directory
    mode: '0755'
    owner: nobody
    group: nogroup

- name: Copy compose from template to host
  ansible.builtin.template:
    src: "templates/docker-compose.yaml"
    dest: "/home/docker-compose/restic/docker-compose.yaml"
    mode: '0755'
    owner: nobody
    group: nogroup

- name: Deploy restic stack
  ansible.builtin.command:
    cmd: docker stack deploy -c /home/docker-compose/restic/docker-compose.yaml nfs_backup_restic

- name: delete compose directory
  ansible.builtin.command:
    cmd: rm -rf /home/docker-compose
