changelog:
  categories:
    - title: "🚨 Breaking Changes"
      labels:
        - "breaking change"
    - title: "🐛 Bug Fixes"
      labels:
        - "bug"
    - title: "🚀 New Application"
      labels:
        - "deployment"
    - title: "✨ New Features"
      labels:
        - "feature"
        - "enhancement"
    - title: "🔧 Chores"
      labels:
        - "chore"
    - title: "📚 Documentation"
      labels:
        - "documentation"
    - title: "📦 Dependencies"
      labels:
        - "dependencies"
