---
- name: Ensure docker-compose is installed
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Setup traefik data directory
  ansible.builtin.file:
    path: /home/docker-compose/traefik/data
    state: directory
    mode: '0755' 
    owner: nobody 
    group: nogroup  

- name: Setup traefik certs directory
  ansible.builtin.file:
    path: /home/docker-compose/traefik/certs
    state: directory
    mode: '0755' 
    owner: nobody 
    group: nogroup  

- name: Setup Traefik directory
  ansible.builtin.file:
    path: /home/docker-compose/traefik
    state: directory
    mode: '0755' 
    owner: nobody 
    group: nogroup  

- name: Copy compose from template to host
  ansible.builtin.template:
    src: "../../../../../compose/traefik/docker-compose.yaml"
    dest: "/home/docker-compose/traefik/docker-compose.yaml"
    mode: '0755' 
    owner: nobody 
    group: nogroup  
  notify:
    - Start Traefik

- name: Deploy Traefik stack
  ansible.builtin.command:
    cmd: docker stack deploy -c /home/docker-compose/traefik/docker-compose.yaml traefik
  register: swarm_check
  changed_when: false