---
# This playbook orchestrates the setup of a Docker Swarm cluster, including NFS configuration, Docker installation,
# Swarm initialization, and network setup. It uses roles to modularize tasks for better reusability and maintainability.

- name: Setup NFS
  hosts: nfs  # Target the NFS server group defined in the inventory.
  become: true  # Execute tasks with elevated privileges (sudo).
  roles:
  - setup_nfs_server  # Use the `setup_nfs_server` role to configure the NFS server.
  # This step ensures that the NFS server is installed, configured, and ready to export shared directories.

- name: Mount NFS
  hosts: cluster  # Target all nodes in the cluster (managers and workers).
  become: true  # Execute tasks with elevated privileges (sudo).
  roles:
  - mount_nfs  # Use the `mount_nfs` role to mount the NFS shares on all nodes.
  # This step ensures that all nodes in the cluster have access to the shared NFS directories.

- name: Set Up Docker
  hosts: cluster  # Target all nodes in the cluster (managers and workers).
  become: true  # Execute tasks with elevated privileges (sudo).
  roles:
  - docker_install  # Use the `docker_install` role to install and configure Docker on all nodes.
  # This step ensures that Docker is installed and configured consistently across all nodes.

- name: Init Docker Swarm
  hosts: manager[0]  # Target the first manager node in the `manager` group.
  become: true  # Execute tasks with elevated privileges (sudo).
  roles:
  - init_swarm  # Use the `init_swarm` role to initialize the Docker Swarm cluster.
  # This step initializes the Swarm cluster and sets up the first manager node.

- name: Join Managers
  hosts: manager  # Target all manager nodes in the `manager` group.
  become: true  # Execute tasks with elevated privileges (sudo).
  roles:
  - join_managers  # Use the `join_managers` role to add additional manager nodes to the Swarm.
  # This step ensures that all manager nodes are part of the Swarm cluster.

- name: Join Workers
  hosts: docker  # Target all worker nodes in the `docker` group.
  become: true  # Execute tasks with elevated privileges (sudo).
  roles:
  - join_workers  # Use the `join_workers` role to add worker nodes to the Swarm.
  # This step ensures that all worker nodes are part of the Swarm cluster.

- name: Assign
  hosts: cluster  # Target all nodes in the cluster (managers and workers).
  become: true  # Execute tasks with elevated privileges (sudo).
  roles:
  - assign_labels  # Use the `assign_labels` role to assign labels to nodes.
  # This step assigns labels to nodes for service placement and organization.

- name: Create Proxy Network
  hosts: manager[0]  # Target the first manager node in the `manager` group.
  become: true  # Execute tasks with elevated privileges (sudo).
  roles:
  - create_proxy_network  # Use the `create_proxy_network` role to create a Docker overlay network.
  # This step sets up the `proxy` network, which is typically used by reverse proxies like Traefik.
