services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    privileged: true
    networks:
      proxy:
      default:
    ports:
      - "8123:8123"
    volumes:
      - /mnt/nfs/docker/home_assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.zigbee == true
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.homeassistant.entrypoints=web"
        - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.spudlab.xyz`)"
        - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
        - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true