---
# This handler file is responsible for restarting the NFS server service.
# Handlers in Ansible are triggered by tasks when changes occur, ensuring that dependent services
# are restarted or reloaded only when necessary. In this case, the NFS server is restarted
# to apply configuration changes or updates made during the playbook execution.

- name: Restart NFS Server
  ansible.builtin.systemd:
    name: nfs-kernel-server  # The name of the NFS server service to manage.
    state: restarted  # Ensure the service is restarted.
    # The `state: restarted` parameter stops and then starts the service, ensuring that any changes
    # to the NFS configuration or dependencies are applied.

# Notes:
# - This handler is typically triggered by tasks that modify NFS-related configurations,
#   such as updating the `/etc/exports` file or installing NFS server dependencies.
# - Restarting the NFS server ensures that any changes to the configuration are applied immediately.
# - Be cautious when restarting the NFS server in production environments, as it may temporarily
#   disrupt access to shared volumes for connected clients.
# - Ensure that the `nfs-kernel-server` service is installed and managed by `systemd` on the target system.
# - If the service name differs (e.g., `nfs-server` on some distributions), update the `name` parameter accordingly.
