---
# This task file is responsible for ensuring that the required NFS directory structure and files for Traefik exist.
# It creates the necessary directories and files with appropriate permissions and ownership.

- name: Create a NFS directory if it does not exist
  ansible.builtin.file:
    path: /mnt/nfs/docker/traefik  # The path to the main NFS directory for Traefik.
    state: directory  # Ensure the path is a directory. If it does not exist, it will be created.
    mode: '0777'  # Set the directory permissions to allow full access (read, write, execute) for all users.
    owner: nobody  # Set the directory owner to `nobody`, a common user for shared resources.
    group: nogroup  # Set the directory group to `nogroup`, a common group for shared resources.
  # This task ensures that the main NFS directory for Traefik is available for use.
  # The `0777` permissions are very permissive and should be used cautiously, especially in production environments.

- name: Setup traefik logs directory
  ansible.builtin.file:
    path: /mnt/nfs/docker/traefik/logs  # The path to the logs directory for Traefik.
    state: directory  # Ensure the path is a directory. If it does not exist, it will be created.
    mode: '0777'  # Set the directory permissions to allow full access (read, write, execute) for all users.
    owner: nobody  # Set the directory owner to `nobody`.
    group: nogroup  # Set the directory group to `nogroup`.
  # This task creates a dedicated logs directory for Traefik to store its log files.
  # The `0777` permissions allow all users to access the logs, which may not be suitable for sensitive environments.

- name: Create multiple files
  ansible.builtin.file:
    path: "/mnt/nfs/docker/traefik/{{ item }}"  # Path to the files to be created inside the NFS directory.
    state: touch  # Ensure the files exist. If they do not exist, they will be created as empty files.
    mode: '0600'  # Set the file permissions to allow read and write access for the owner only.
  with_items:
  - acme.json  # File for storing Let's Encrypt certificates and keys.
  # This task ensures that the required configuration files for Traefik exist in the NFS directory.
  # The `0600` permissions restrict access to the owner, which is critical for sensitive files like `acme.json`.

# Notes:
# - The `0777` permissions for directories are very permissive and allow full access to all users.
#   Use caution when setting such permissions, especially in production environments.
# - The `0600` permissions for files like `acme.json` are more restrictive and are suitable for sensitive data.
# - The `nobody` user and `nogroup` group are commonly used for shared resources in NFS setups.
#   Ensure that these settings align with your NFS server's configuration.
# - Always test changes in a staging environment before applying them to production systems.
# - Ensure that the NFS mount point (`/mnt/nfs/docker`) is already mounted and accessible on the target system.
