---
# This task file is responsible for removing a node from a Docker Swarm cluster.
# It uses the `docker swarm leave` command to ensure the node leaves the Swarm.
# The `--force` flag is used to forcibly remove the node, even if it is a manager.

- name: leave swarm
  ansible.builtin.shell: docker swarm leave --force
  # The `docker swarm leave` command removes the node from the Swarm cluster.
  # - `--force`: Ensures the node leaves the Swarm, even if it is a manager or part of an active cluster.
  # This is useful for resetting the node or reconfiguring it outside of the Swarm.

  ignore_errors: yes
  # The `ignore_errors` directive ensures that the playbook continues even if this task fails.
  # This is useful in cases where the node is not part of a Swarm, as the command will fail in such scenarios.

  changed_when: false
  # The `changed_when` directive ensures that this task does not mark the playbook as "changed."
  # This is useful for idempotency, as leaving a Swarm does not necessarily indicate a configuration change.

  register: leave_swarm
  # The `register` directive stores the output of the command in the `leave_swarm` variable.
  # This can be used for debugging or logging purposes in subsequent tasks.

# Notes:
# - This task assumes that Docker is installed and running on the target node.
# - The `--force` flag should be used with caution, especially on manager nodes, as it forcibly removes the node.
# - If the node is not part of a Swarm, the command will fail, but the `ignore_errors` directive ensures the playbook continues.
# - This task is useful for resetting nodes or removing them from a Swarm cluster during decommissioning or reconfiguration.
