---
- name: Ensure docker-compose is installed
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Setup Home Assistant directory
  ansible.builtin.file:
    path: /home/docker-compose/home-assistant
    state: directory
    mode: '0755'
    owner: nobody
    group: nogroup

- name: Copy compose from template to host
  ansible.builtin.template:
    src: "templates/docker-compose.yaml"
    dest: "/home/docker-compose/home_assistant/docker-compose.yaml"
    mode: '0755'
    owner: nobody
    group: nogroup
  notify:
  - Start Home Assistant

- name: Deploy Home Assistant stack
  ansible.builtin.command:
    cmd: docker stack deploy -c /home/docker-compose/home_assistant/docker-compose.yaml homeassistant
  register: swarm_check
  changed_when: false
