---
# This task file is responsible for deploying the Cioban stack using Docker Swarm.
# It ensures that Docker and docker-compose are installed and running, removes any existing services,
# sets up the required directory structure, deploys the stack, and cleans up temporary files.

- name: Run shared Docker prerequisites and cleanup
  ansible.builtin.include_tasks: "{{ role_path }}/../../../_shared/roles/docker_prereqs_and_stop/tasks/main.yml"
  vars:
    docker_prereqs_and_stop_services_to_stop:
      - cioban_cioban

- name: Set up Cioban directory
  ansible.builtin.file:
    path: /home/docker-compose/cioban  # The path to the directory to be created.
    state: directory  # Ensure the path is a directory.
    mode: '0755'  # Set the directory permissions (read, write, execute for owner; read and execute for others).
    owner: nobody  # Set the directory owner to `nobody`.
    group: nogroup  # Set the directory group to `nogroup`.
  # This task creates the directory structure required for the deployment.

- name: Copy Compose from template to host
  ansible.builtin.template:
    src: "templates/docker-compose.yml"  # Path to the Jinja2 template for the docker-compose file.
    dest: "/home/docker-compose/cioban/docker-compose.yaml"  # Destination path for the docker-compose file.
    mode: '0755'  # Set the file permissions (read, write, execute for owner; read and execute for others).
    owner: nobody  # Set the file owner to `nobody`.
    group: nogroup  # Set the file group to `nogroup`.
  # This task copies the docker-compose template to the target system, ensuring it is ready for deployment.

- name: Deploy Cioban stack
  community.docker.docker_stack:
    name: cioban
    compose:
      - /home/docker-compose/cioban/docker-compose.yaml
    state: present
    with_registry_auth: true
  register: deploy_swarm_check  # Store the output of the command in the `swarm_check` variable.
  changed_when: false  # Ensure this task does not mark the playbook as "changed."
  # This task deploys the Cioban stack to the Docker Swarm cluster.

- name: Delete compose directory
  ansible.builtin.file:
    path: /home/docker-compose
    state: absent
  # This task cleans up the temporary files and directories created during the deployment process.

# Notes:
# - Ensure that Docker and Docker Swarm are properly configured on the target system before running this playbook.
# - The `docker-compose.yml` template should define the services, networks, and volumes required for the Cioban stack.
# - The `--with-registry-auth` flag ensures that private registry credentials are passed to the Swarm nodes.
# - The cleanup step (`delete compose directory`) is optional and can be removed if the compose files need to be retained.
# - Use caution when setting permissions (`0755`) and ownership (`nobody:nogroup`) to avoid security risks.
