---
# This task file is responsible for deploying the Cioban stack using Docker Swarm.
# It ensures that Docker and docker-compose are installed and running, removes any existing services,
# sets up the required directory structure, deploys the stack, and cleans up temporary files.

- name: Run shared Docker prerequisites and cleanup
  ansible.builtin.include_role:
    name: docker_prereqs_and_stop
  vars:
    docker_prereqs_and_stop_services_to_stop:
      - cioban_cioban
  # This task includes a shared role that ensures Docker and Docker Compose are installed and running.
  # It also removes any existing Docker Swarm services related to Cioban to ensure a clean deployment.

- name: Deploy Services
  ansible.builtin.include_role:
    name: copy_and_deploy
  vars:
      stack_name: cioban

- name: Clean up compose directory
  ansible.builtin.include_role:
    name: cleanup

# Notes:
# - Ensure that Docker and Docker Swarm are properly configured on the target system before running this playbook.
# - The `docker-compose.yml` template should define the services, networks, and volumes required for the Cioban stack.
# - The `--with-registry-auth` flag ensures that private registry credentials are passed to the Swarm nodes.
# - The cleanup step (`delete compose directory`) is optional and can be removed if the compose files need to be retained.
# - Use caution when setting permissions (`0755`) and ownership (`nobody:nogroup`) to avoid security risks.
