---
# This task file is responsible for creating a Docker overlay network named "proxy".
# The "proxy" network is typically used by Traefik or other reverse proxies to route traffic
# between services in a Docker Swarm cluster. Overlay networks allow containers running on
# different nodes in the Swarm to communicate with each other.

- name: create proxy network for traefik
  community.docker.docker_network:  # Use the `docker_network` module from the `community.docker` collection.
    name: proxy  # The name of the network to be created.
    # The `name` parameter specifies the name of the Docker network. In this case, it is "proxy".

    driver: overlay  # The network driver to use.
    # The `driver` parameter specifies the type of network to create. 
    # "overlay" is used for multi-host networking in Docker Swarm, enabling communication between containers on different nodes.

    state: present  # Ensure the network is created and exists.
    # The `state` parameter determines the desired state of the network:
    # - `present`: Ensures the network exists. If it doesn't, it will be created.
    # - `absent`: Ensures the network is removed if it exists.

# Notes:
# - Ensure that the `community.docker` collection is installed before running this task.
#   You can install it using the following command:
#   ```bash
#   ansible-galaxy collection install community.docker
#   ```
# - The "proxy" network is essential for services like Traefik to function correctly in a Docker Swarm cluster.
# - This task assumes that Docker Swarm is already initialized on the cluster.
# - Overlay networks require a properly configured Swarm cluster with at least one manager node.
