cluster:
  children:
    docker:
    manager:

docker:
    hosts:
      docker-01:
        swarm_labels:
          label_example: "example"
      docker-[02:06]:

manager:
    hosts:      
      manager-[01:02]:
      nfs:
        swarm_labels:
          zigbee: "true"

cluster-support:
  hosts:
    nfs: