services:

  paperless-broker:
    image: docker.io/library/redis:8
    container_name: paperless-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    container_name: paperless
    depends_on:
      - paperless-broker
      - paperless-gotenberg
      - paperless-tika
    ports:
      - "8000:8000"
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - export:/usr/src/paperless/export
      - consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://paperless-broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://paperless-tika:9998

  paperless-gotenberg:
    image: docker.io/gotenberg/gotenberg:8.27
    restart: unless-stopped
    container_name: paperless-gotenberg
    ports:
      - "3000:3000"
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  paperless-tika:
    image: docker.io/apache/tika:latest
    container_name: paperless-tika
    restart: unless-stopped
    ports:
      - "9998:9998"

volumes:
  redisdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/joseph/paperless-test/redis

  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/joseph/paperless-test/data

  media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/joseph/paperless-test/media

  export:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/joseph/paperless-test/export

  consume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/joseph/paperless-test/consume