---
# This task file is responsible for assigning labels to Docker Swarm nodes.
# Labels are key-value pairs that can be used to organize and manage nodes in a Swarm cluster.
# These labels are often used for service placement constraints, ensuring that services run on specific nodes.

- name: Set Labels on swarm nodes
  community.docker.docker_node:  # Use the `docker_node` module from the `community.docker` collection.
        hostname: "{{ inventory_hostname_short }}"  # The short hostname of the current node.
        # The `hostname` parameter specifies the node to which the labels will be applied.
        # It uses the `inventory_hostname_short` variable, which is derived from the Ansible inventory.

        labels: "{{ swarm_labels }}"  # The labels to assign to the node.
        # The `labels` parameter expects a dictionary of key-value pairs.
        # Example: `swarm_labels: {"role": "worker", "zone": "us-east"}`

        labels_state: replace  # Replace any existing labels with the new ones.
        # The `labels_state` parameter determines how labels are applied:
        # - `replace`: Replaces all existing labels with the specified ones.
        # - `merge`: Merges the specified labels with the existing ones.

  delegate_to: "manager-01"  # Delegate the task to the Swarm manager node.
  # The `delegate_to` directive ensures that the task is executed on the specified manager node
  # (in this case, `manager-01`), as only manager nodes can modify Swarm node labels.

  when: swarm_labels is defined  # Only run this task if the `swarm_labels` variable is defined.
  # The `when` clause ensures that the task is skipped if no labels are specified for the node.

# Notes:
# - Ensure that the `community.docker` collection is installed before running this task.
#   You can install it using the following command:
#   ```bash
#   ansible-galaxy collection install community.docker
#   ```
# - The `swarm_labels` variable should be defined in the inventory or group variables file.
# - This task assumes that the Swarm cluster is already initialized and the nodes are part of the cluster.
