---
- name: install nfs server depenedences
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - nfs-kernel-server
  - nfs-common

- name: Reload systemd to recognize NFS changes
  ansible.builtin.systemd:
    daemon_reload: true

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /mnt/nfs/docker
    state: directory
    mode: '7777'
    owner: nobody
    group: nogroup

- name: Mount an NFS volume
  ansible.posix.mount:
    src: "nfs.local:/exports/docker"
    path: /mnt/nfs/docker
    opts: rw,sync,hard
    state: mounted
    fstype: nfs
