---
# This playbook ensures the deployment of a blog service using Docker Swarm.
# It performs tasks such as installing dependencies, managing Docker services,
# setting up directories, deploying the stack, and cleaning up temporary files.

# Task 1: Run shared Docker prerequisites and service cleanup
- name: Run shared Docker prerequisites and cleanup
  ansible.builtin.include_role:
    name: docker_prereqs_and_stop
  vars:
    docker_prereqs_and_stop_services_to_stop:
      - blog_blog
  # This task includes a shared role that ensures Docker and Docker Compose are installed and running.
  # It also removes any existing Docker Swarm services related to the blog to ensure a clean deployment.

- name: Deploy Services
  ansible.builtin.include_role:
    name: copy_and_deploy
  vars:
      stack_name: blog


- name: Clean up compose directory
  ansible.builtin.include_role:
    name: cleanup
