---
- name: Start Blog 
  community.docker.docker_compose_v2:
    project_src: /home/docker-compose/blog
    state: present
    restarted: true

- name: delete compose directory
  ansible.builtin.command:
    cmd: rm -rf /home/docker-compose 