---
# NFS Directory Preparation for Immich Deployment
# This task file ensures all required NFS directories exist before deploying Immich services.
# It creates the complete directory structure needed for persistent data storage.

- name: Create required NFS directories if they do not exist
  # Creates all necessary NFS directories for Immich application data storage.
  # Uses a loop to efficiently create multiple directories with consistent permissions.
  # This task is idempotent - it will only create directories that don't already exist.
  
  ansible.builtin.file:
    path: "{{ item }}"
    # The directory path to create, supplied by the loop variable.
    # Each path in the loop will be processed sequentially.
    
    state: directory
    # Ensures the path exists as a directory.
    # If the path doesn't exist, it will be created.
    # If it exists but is not a directory, the task will fail.
    
    mode: '0777'
    # Sets directory permissions to allow full access (read, write, execute) for all users.
    # This is necessary for Docker containers running as different UIDs to access the storage.
    # Note: 0777 is permissive but required for multi-container access in NFS environments.
    
    owner: nobody
    # Sets the directory owner to 'nobody', a standard unprivileged user.
    # This prevents ownership conflicts when containers access the shared storage.
    # The 'nobody' user is commonly used for shared resources in NFS setups.
    
    group: nogroup
    # Sets the directory group to 'nogroup', a standard unprivileged group.
    # Matches the owner setting for consistent unprivileged access.
    # Ensures containers can access directories regardless of their internal user mapping.
    
  loop:
    - /mnt/nfs/docker/immich
    # Root directory for all Immich data on the NFS share.
    # Serves as the parent directory for all Immich-related storage.
    
    - /mnt/nfs/docker/immich/backups
    # Directory for database backups and configuration exports.
    # Used by backup services and manual backup procedures.
    # Critical for disaster recovery and data migration scenarios.
    
    - /mnt/nfs/docker/immich/upload
    # Primary storage directory for user-uploaded photos and videos.
    # This is where all media files are permanently stored.
    # Should have sufficient space for the expected media library size.
    
    - /mnt/nfs/docker/immich/ml
    # Cache directory for machine learning models and processing data.
    # Stores downloaded AI models and temporary processing files.
    # Improves performance by caching models between container restarts.
    
    - /mnt/nfs/docker/immich/database
    # PostgreSQL data directory for persistent database storage.
    # Contains all application data including metadata and user accounts.
    # Critical directory that must be backed up regularly.

# Prerequisites:
# - The NFS mount point (/mnt/nfs) must already be mounted and accessible
# - The NFS server must be configured to allow the required permissions
# - The target system must have appropriate network connectivity to the NFS server
