---
# This file defines group variables for the Docker Swarm playbooks.
# These variables are used to authenticate with a private Docker registry.
# The credentials and registry URL are securely retrieved from an Ansible Vault to protect sensitive information.

registry_user: "{{ vault_registry_user }}" # The username for the Docker registry.
# This variable retrieves the username from the Ansible Vault.
# Replace "vault_registry_user" with the actual username if not using a vault, but be cautious
# about storing sensitive information in plain text.

registry_password: "{{ vault_registry_password }}" # The password for the Docker registry.
# This variable retrieves the password from the Ansible Vault.
# Replace "vault_registry_password" with the actual password if not using a vault, but avoid
# exposing sensitive credentials in plain text.

registry_url: "{{ vault_registry_url }}" # The URL of the Docker registry.
# This variable retrieves the registry URL from the Ansible Vault.
# Replace "vault_registry_url" with the actual registry URL if not using a vault.
# Example: "https://index.docker.io/v1/" for Docker Hub or a custom URL for private registries.

# NFS Server Configuration
# This variable stores the hostname or IP address of the NFS server
# It is dynamically set to the first host in the 'nfs_servers' group from the inventory
# This allows the playbook to automatically use the correct NFS server without hardcoding IP addresses
# Note: This dynamic resolution relies on the 'ansible_default_ipv4' variable being set on the NFS server host.
#       Ensure that the NFS server host has a default IPv4 address configured and that this variable is available
#       in the inventory. Ansible typically sets this variable automatically if the host has a default IPv4 address.
nfs_server_host: "{{ hostvars[groups['nfs_servers'][0]].ansible_default_ipv4.address }}"

# NFS access restriction configuration
# This variable defines which hosts/networks are allowed to access the NFS exports
# It is used in the exports.j2 template to configure the NFS server's exports file
# Format: IP address or hostname with optional netmask or CIDR notation
#
# Common values:
# - "192.168.1.0/24"            # Allow access from entire subnet (192.168.1.0 through 192.168.1.255)
# - "10.0.0.5"                  # Allow access from a single IP address
# - "*.example.com"             # Allow access from all hosts in example.com domain
# - "@trusted_network"          # Allow access from a netgroup (if NIS is configured)
# - "10.0.0.0/8 192.168.0.0/16" # Multiple networks separated by spaces
#
# Security considerations:
# - Avoid using "*" which allows access from any host, unless behind a secure firewall
# - Consider using more restrictive options for production environments
# - When possible, explicitly list the IPs of Docker Swarm nodes instead of entire subnets
# - For high-security environments, also consider implementing firewall rules (iptables)
#
# This value is retrieved from Ansible Vault for security
nfs_restriction: "{{ vault_nfs_restriction }}"

# Security Note:
# - Always use Ansible Vault to store sensitive information like usernames, passwords, and URLs.
# - Avoid hardcoding sensitive credentials directly in this file to prevent unauthorized access.
