---
- name: Ensure docker-compose is installed
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Remove service
  docker_swarm_service:
    name: rclone_rclone
    state: absent
  ignore_errors: true

- name: Setup rclone directory
  ansible.builtin.file:
    path: /home/docker-compose/rclone
    state: directory
    mode: '0755'
    owner: nobody
    group: nogroup

- name: Copy compose from template to host
  ansible.builtin.template:
    src: "templates/docker-compose.yaml"
    dest: "/home/docker-compose/rclone/docker-compose.yaml"
    mode: '0755'
    owner: nobody
    group: nogroup

- name: Deploy rclone stack
  ansible.builtin.command:
    cmd: docker stack deploy -c /home/docker-compose/rclone/docker-compose.yaml rclone

- name: delete compose directory
  ansible.builtin.command:
    cmd: rm -rf /home/docker-compose
