- name: Ensure docker-compose is installed
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Setup traefik directory
  ansible.builtin.file:
    path: /home/docker-compose/traefik
    state: directory
    mode: '0755'

- name: Remove service
  docker_swarm_service:
    name: traefik_traefik
    state: absent
  ignore_errors: true

- name: itterate over my_environment in group vars yml
  docker_secret:
    name: "{{ item.key }}"
    data: "{{ item.value }}"
    force: true
  with_dict: "{{ secrets }}"
  no_log: true

- name: Copy compose from template to host
  ansible.builtin.template:
    src: "templates/docker-compose.yaml"
    dest: "/home/docker-compose/traefik/docker-compose.yaml"
    mode: '0755'

- name: Deploy traefik  stack
  ansible.builtin.command:
    cmd: docker stack deploy -c /home/docker-compose/traefik/docker-compose.yaml traefik
  register: swarm_check
  changed_when: false

- name: delete compose directory
  ansible.builtin.command:
    cmd: rm -rf /home/docker-compose 