---
- name: Create a NFS directory if it does not exist
  ansible.builtin.file:
    path: /mnt/nfs/docker/home_assistant
    state: directory
    mode: '7777'
    owner: nobody
    group: nogroup

- name: Setup Home Assistant directory
  ansible.builtin.file:
    path: /home/docker-compose/home_assistant
    state: directory
    mode: '0755' 
    owner: nobody 
    group: nogroup  

- name: Create multiple files
  ansible.builtin.file: 
      path: "/mnt/nfs/docker/home_assistant/{{ item }}"
      state: touch
  with_items:
    - automations.yaml
    - scenes.yaml
    - scripts.yaml

- name: copy default configuration
  template:
    src: "templates/configuration.yaml.j2"
    dest: "/mnt/nfs/docker/home_assistant/configuration.yaml"
    force: false
