---
- name: Ensure docker-compose is installed
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Remove service
  docker_swarm_service:
    name: gitea_gitea
    state: absent
  ignore_errors: true

- name: Setup Gitea directory
  ansible.builtin.file:
    path: /home/docker-compose/gitea
    state: directory
    mode: '0755'
    owner: nobody
    group: nogroup

- name: Copy compose from template to host
  ansible.builtin.template:
    src: "templates/docker-compose.yml"
    dest: "/home/docker-compose/gitea/docker-compose.yaml"
    mode: '0755'
    owner: nobody
    group: nogroup

- name: Deploy Gitea stack
  ansible.builtin.command:
    cmd: docker stack deploy -c /home/docker-compose/gitea/docker-compose.yaml gitea 
  register: swarm_check
  changed_when: false

- name: delete compose directory
  ansible.builtin.command:
    cmd: rm -rf /home/docker-compose 
