---
# This playbook is responsible for shutting down all nodes in the cluster gracefully.
# It targets all hosts in the "cluster" group and ensures that the shutdown process is delayed
# to allow any final tasks or processes to complete before powering off.

- hosts: cluster  # Target all hosts in the "cluster" group defined in the inventory.
  become: true  # Run all tasks with elevated privileges (e.g., sudo) to allow system shutdown.

  tasks:  # Define the list of tasks to execute.

  # Task 1: Delay shutting down the remote node
  - name: Delay shutting down the remote node
    community.general.shutdown:  # Use the shutdown module from the community.general collection.
      delay: 60  # Delay the shutdown by 60 seconds to allow processes to finish gracefully.
    # This task sends a shutdown signal to the remote node, delaying the shutdown by 60 seconds.
    # The delay ensures that any critical processes or services have time to terminate properly
    # before the system powers off.
