---
# These tasks deploy and configure restic backup services on Docker Swarm
# The deployment includes backup, prune, and check services that work together
# to create a complete backup solution for NFS-shared data

# Run common Docker prerequisites and remove old services before redeploying.
- name: Run shared Docker prerequisites and cleanup
  ansible.builtin.include_role:
    name: docker_prereqs_and_stop
  vars:
    docker_prereqs_and_stop_services_to_stop:
      - nfs_backup_restic_backup
      - nfs_backup_restic_prune
      - nfs_backup_restic_check
  # This task ensures Docker and Docker Compose are installed and running on the target system.
  # It also removes any existing Docker Swarm services related to the NFS backup stack to
  # ensure a clean deployment environment.

- name: Deploy Services
  ansible.builtin.include_role:
    name: copy_and_deploy
  vars:
    copy_and_deploy_stack_name: nfs_backup_restic

- name: Clean up compose directory
  ansible.builtin.include_role:
    name: cleanup
