---

# This role ensures that the proper directories exist for rClone
# configuration persistence via NFS, as well as local directories for
# Docker Compose configuration files.

# Task 1: Create rClone config directory on NFS share
- name: Create a NFS directory if it does not exist
  ansible.builtin.file:
    path: /mnt/nfs/docker/rclone/config  # Path on NFS mount where rClone config will be stored
    state: directory                     # Ensure this is a directory
    mode: '0777'                         # Full permissions for all users
                                         # This is permissive to avoid permission issues with containers
                                         # Consider restricting in production if security is a concern
    owner: nobody                        # The 'nobody' user typically used for NFS shared resources
    group: nogroup                       # The 'nogroup' group typically used for NFS shared resources
  # This directory will persist rClone configurations across container restarts and redeployments
  # It's mounted into the container at runtime to store remote configurations, credentials, etc.
  # Note: The NFS share must be properly mounted at /mnt/nfs before this task runs

# Task 2: Create local directory for Docker Compose deployment files
- name: Setup rClone directory
  ansible.builtin.file:
    path: /home/docker-compose/rclone/config  # Local path for docker-compose configuration
    state: directory                          # Ensure this is a directory
    mode: '0755'                              # More restrictive permissions for local directory
                                              # Owner can read/write/execute, others can read/execute
    owner: nobody                             # The 'nobody' user for minimal privileges
    group: nogroup                            # The 'nogroup' group for minimal privileges
  # This directory is used temporarily during deployment to store Docker Compose files
  # These files will be used by the deploy_rclone role to create the Docker Swarm stack
  # Note: This directory doesn't need to persist after deployment, but creating it
  # separately helps with troubleshooting if the deployment fails
