services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.10.9
    container_name: homepage
    environment:
      PUID: 1003
      PGID: 1003
    ports:
      - 3000:3000
    volumes:
      - ./docker/homepage/config:/app/config 
    restart: unless-stopped
    networks:
      - host

networks:
  host:
    name: host
    external: true