services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.10.9
    container_name: homepage
    environment:
      PUID: 1003
      PGID: 1003
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config 
    env_file:
      - stack.env
    