---
- name: Ensure docker-compose is installed
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Create a NFS directory if it does not exist
  ansible.builtin.file:
    path: /mnt/nfs/docker/portainer_data
    state: directory
    mode: '7777'
    owner: nobody
    group: nogroup

- name: Setup Portainer directory
  ansible.builtin.file:
    path: /home/docker-compose/portainer
    state: directory
    mode: '0755' 
    owner: nobody 
    group: nogroup  

- name: Copy compose from template to host
  ansible.builtin.template:
    src: "../../../../../compose/portainer/docker-compose.yaml"
    dest: "/home/docker-compose/portainer/docker-compose.yaml"  
    mode: '0755' 
    owner: nobody 
    group: nogroup  
  notify:
    - Start Portainer

- name: Deploy Portainer stack
  ansible.builtin.command:
    cmd: docker stack deploy -c /home/docker-compose/portainer/docker-compose.yaml portainer
  register: swarm_check
  changed_when: false