---
# This file defines group variables for the "set-up-machine" playbook.
# These variables are used to configure the machines in the cluster, such as setting up SSH keys.
# The values in this file are shared across all hosts in the group.

public_key: "/.ssh/homelab.pub" # This is the path to the public SSH key.
# The `public_key` variable specifies the location of the public key file that will be used
# to configure passwordless SSH access to the machines in the cluster.
# - Ensure that the path is correct and points to the public key file you want to use.
# - Example: "/home/username/.ssh/id_rsa.pub" for a typical SSH key setup.
# - This key will be copied to the target machines' `~/.ssh/authorized_keys` file to allow
#   secure, passwordless access.
# - If the key does not exist at the specified path, generate one using the `ssh-keygen` command:
#   ```bash
#   ssh-keygen -t rsa -b 4096 -C "your_email@example.com" -f ~/.ssh/homelab
#   ```
#   This will create a private key (`homelab`) and a public key (`homelab.pub`) in the `~/.ssh` directory.

# Security Note:
# - Ensure that the private key corresponding to this public key is securely stored and not shared.
# - Avoid hardcoding sensitive information in this file. Use Ansible Vault if additional sensitive
#   variables (e.g., private keys or passwords) are required.
