services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    privileged: true
    networks:
      proxy:
      default:
    volumes:
      - /mnt/nfs/docker/home_assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.zigbee == true
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.homeassistant.entrypoints=web"
        - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.{{ general.domain }}`)"
        - "traefik.http.middlewares.homeassistant-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.homeassistant.middlewares=homeassistant-https-redirect"
        - "traefik.http.routers.homeassistant-secure.entrypoints=websecure"
        - "traefik.http.routers.homeassistant-secure.rule=Host(`homeassistant.{{ general.domain }}`)"
        - "traefik.http.routers.homeassistant-secure.tls=true"
        - "traefik.http.routers.homeassistant-secure.service=homeassistant"
        - "traefik.http.routers.homeassistant-secure.tls.certresolver=letsencrypt"
        - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
        - "traefik.http.services.homeassistant.loadbalancer.passhostheader=true"
        - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true