---
- name: Create a NFS directory if it does not exist
  ansible.builtin.file:
    path: /mnt/nfs/docker/portainer_data
    state: directory
    mode: '7777'
    owner: nobody
    group: nogroup

- name: Setup Portainer directory
  ansible.builtin.file:
    path: /home/docker-compose/portainer
    state: directory
    mode: '0755'
    owner: nobody
    group: nogroup
