services:
  coredns:
    image: coredns/coredns:1.12.0
    container_name: coredns
    command: -conf /etc/coredns/Corefile -dns.port 53
    ports:
      - "53:53"
      - "53:53/udp"
      - "8080:8080"
    volumes:
      - ./config/coredns/Corefile:/etc/coredns/Corefile
      - ./config/coredns/db.spudlab.xyz:/etc/coredns/db.spudlab.xyz
    privileged: true
    restart: unless-stopped
