services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.10.9
    container_name: homepage
    environment:
      PUID: 1003
      PGID: 1003
    ports:
      - 80:3000
    volumes:
      - .config/homepage:/app/config 
    restart: unless-stopped