---
- name: Power tune Raspberry Pi cluster
  hosts: cluster
  become: true
  gather_facts: true

  vars:
    # Adjust if your Pis still use /boot/config.txt on older OS
    rpi_boot_config: "/boot/firmware/config.txt"
    rpi_cmdline: "/boot/firmware/cmdline.txt"

    # PoE HAT fan curve (in millidegrees C)
    # Tune these if you want it to kick in earlier/later
    poe_fan_temp0: 60000   # fan off below this
    poe_fan_temp1: 65000
    poe_fan_temp2: 70000
    poe_fan_temp3: 75000   # full speed above this

  handlers:
    - name: reboot rpi
      ansible.builtin.reboot:
        msg: "Rebooting to apply power-tuning settings"
        connect_timeout: 30
        reboot_timeout: 600
        test_command: "whoami"

  tasks:

    - name: Ensure vcgencmd available (optional)
      ansible.builtin.package:
        name: libraspberrypi-bin
        state: present

    # --- RUNTIME HDMI OFF (immediate) ------------------------

    - name: Turn off HDMI output now (ignore errors)
      ansible.builtin.shell: |
        vcgencmd display_power 0 || true
      changed_when: false
      tags: [hdmi, runtime]

    # --- CONFIG.TXT POWER TWEAKS -----------------------------

    - name: Ensure boot config exists
      ansible.builtin.stat:
        path: "{{ rpi_boot_config }}"
      register: bootconf

    - name: Fallback to /boot/config.txt if /boot/firmware not present
      ansible.builtin.set_fact:
        rpi_boot_config: "/boot/config.txt"
      when: not bootconf.stat.exists

    - name: Add power-saving block to config.txt
      ansible.builtin.blockinfile:
        path: "{{ rpi_boot_config }}"
        marker: "# {mark} ANSIBLE POWER TUNING"
        block: |
          # --- HDMI off / display power saving ---
          hdmi_blanking=2
          disable_fw_kms_setup=1
          display_default_lcd=0
          enable_tvout=0

          # Comment out KMS overlays if they appear elsewhere in this file
          # (Ansible will also try to comment them below)
          #dtoverlay=vc4-kms-v3d
          #dtoverlay=vc4-fkms-v3d

          # --- Disable onboard Wi-Fi & Bluetooth ---
          dtoverlay=disable-wifi
          dtoverlay=disable-bt

          # --- PoE HAT fan tuning (less aggressive at low temps) ---
          dtoverlay=rpi-poe,poe_fan_temp0={{ poe_fan_temp0 }},poe_fan_temp1={{ poe_fan_temp1 }},poe_fan_temp2={{ poe_fan_temp2 }},poe_fan_temp3={{ poe_fan_temp3 }}

          # --- Optional mild underclock (safe defaults) ---
          # Uncomment if you want to cap max freq a bit
          # For Pi 4 (default 1500), this is basically no change:
          #arm_freq=1500
          # For Pi 5 (default 2400), this is a gentle cap:
          #arm_freq=1800
      notify: reboot rpi
      tags: [config, wifi, bt, hdmi, poe]

    - name: Comment out vc4-kms-v3d overlay if present
      ansible.builtin.replace:
        path: "{{ rpi_boot_config }}"
        regexp: '^(dtoverlay=vc4-(fkms|kms)-v3d)'
        replace: '#\1'
      notify: reboot rpi
      tags: [config, hdmi]

    # --- CMDLINE.TXT: CPU GOVERNOR ---------------------------

    - name: Ensure cmdline exists
      ansible.builtin.stat:
        path: "{{ rpi_cmdline }}"
      register: cmdline_stat

    - name: Fallback to /boot/cmdline.txt if /boot/firmware not present
      ansible.builtin.set_fact:
        rpi_cmdline: "/boot/cmdline.txt"
      when: not cmdline_stat.stat.exists

    - name: Ensure powersave CPU governor kernel param is present
      ansible.builtin.lineinfile:
        path: "{{ rpi_cmdline }}"
        backrefs: true
        regexp: '^(.*)$'
        line: '\1 cpufreq.default_governor=powersave'
      notify: reboot rpi
      tags: [cpu]

    # --- SYSTEMD SERVICE TO ENFORCE GOVERNOR ON BOOT --------

    - name: Create CPU powersave service
      ansible.builtin.copy:
        dest: /etc/systemd/system/cpupowersave.service
        mode: '0644'
        content: |
          [Unit]
          Description=Set CPU governor to powersave
          After=multi-user.target

          [Service]
          Type=oneshot
          ExecStart=/bin/sh -c 'for c in /sys/devices/system/cpu/cpu[0-9]*; do echo powersave > "$c/cpufreq/scaling_governor" 2>/dev/null || true; done'

          [Install]
          WantedBy=multi-user.target
      notify: reboot rpi
      tags: [cpu]

    - name: Enable CPU powersave service
      ansible.builtin.systemd:
        name: cpupowersave.service
        enabled: true
      tags: [cpu]

    # --- UDEV RULES FOR USB/NVME AUTOSUSPEND ----------------

    - name: Create udev rule for USB/NVMe autosuspend
      ansible.builtin.copy:
        dest: /etc/udev/rules.d/99-nvme-usb-autosuspend.rules
        mode: '0644'
        content: |
          # Enable autosuspend for USB storage / NVMe enclosures
          ACTION=="add", SUBSYSTEM=="usb", TEST=="power/control", ATTR{power/control}="auto"
      notify: reboot rpi
      tags: [nvme, usb]

    - name: Trigger udev so autosuspend rule takes effect
      ansible.builtin.shell: udevadm control --reload-rules && udevadm trigger
      tags: [nvme, usb]

    # --- MASK RFKILL SERVICES (belt & braces for WiFi/BT) ----

    - name: Mask rfkill-related services
      ansible.builtin.systemd:
        name: "{{ item }}"
        masked: true
        enabled: false
        state: stopped
      loop:
        - wpa_supplicant.service
        - bluetooth.service
      ignore_errors: true
      tags: [wifi, bt]

