---
# This playbook is responsible for logging into a private Docker registry on all nodes in the cluster.
# It uses credentials and the registry URL defined in the group variables file (`group_vars/all.yml`).
# The credentials are securely retrieved from an Ansible Vault to ensure sensitive information is protected.

- name: Docker login to private registry
  hosts: cluster  # Target all hosts in the "cluster" group defined in the inventory.
  become: true  # Run all tasks with elevated privileges (e.g., sudo) to ensure access to Docker commands.

  tasks:  # Define the list of tasks to execute.

    # Task 1: Log in to the private Docker registry
    - name: Docker login to private registries
      community.docker.docker_login:
        username: "{{ item.username }}"
        password: "{{ item.password }}"
        registry_url: "{{ item.registry_url }}"
      loop: "{{ vault.docker_registries }}"
      loop_control:
        label: "{{ item.registry_url }}"
      no_log: true
      changed_when: false
      # This task logs into the private Docker registry using the credentials and URL provided in the group variables.
      # The credentials (`registry_user` and `registry_password`) and the registry URL (`registry_url`) are securely
      # retrieved from the Ansible Vault to avoid exposing sensitive information in plain text.
