---
# This task file is responsible for ensuring that the required NFS directory for Gitea exists.
# It creates the directory with the appropriate permissions, ownership, and group settings if it does not already exist.

- name: Create a NFS directory if it does not exist
  ansible.builtin.file:
    path: /mnt/nfs/docker/gitea  # The path to the NFS directory to be created.
    state: directory  # Ensure the path is a directory. If it does not exist, it will be created.
    mode: '0777'  # Set the directory permissions to allow full access (read, write, execute) for all users.
    owner: nobody  # Set the directory owner to `nobody`, a common user for shared resources.
    group: nogroup  # Set the directory group to `nogroup`, a common group for shared resources.
  # This task ensures that the NFS directory is available for use by the Gitea service.

# Notes:
# - The `0777` permissions are very permissive and allow full access to all users. 
#   Use caution when setting such permissions, especially in production environments.
# - The `nobody` user and `nogroup` group are commonly used for shared resources in NFS setups.
#   Ensure that these settings align with your NFS server's configuration.
# - This task assumes that the NFS mount point (`/mnt/nfs/docker`) is already mounted and accessible on the target system.
# - If the NFS mount is not yet configured, ensure that it is properly set up before running this task.
# - Always test changes in a staging environment before applying them to production systems.